title: Self Description
author: MangoMaster
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Self-description of MangoMaster

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
